"""FastAPI application entry point."""
from __future__ import annotations

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from .config import settings
from .database import Base, SessionLocal, engine, init_fts
from .routers import action_items, auth, engagement, meetings, notes, search, workspace
from .services.transcript_parser import TranscriptParseError

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(_: FastAPI):
    """Create the schema, the FTS index, and seed an empty database."""
    Base.metadata.create_all(bind=engine)
    init_fts()

    if settings.auto_seed:
        from . import models
        from .seed.seed import seed_database

        with SessionLocal() as db:
            if db.query(models.Meeting).count() == 0:
                logger.info("Empty database detected — seeding sample workspace.")
                seed_database(db)
    yield


app = FastAPI(
    title=settings.app_name,
    version="1.0.0",
    description=(
        "Backend for a Fireflies.ai-style meeting notes and transcription workspace. "
        "Transcripts are seeded or uploaded rather than produced by speech-to-text; "
        "summaries are generated by a deterministic extractive engine, or by Claude "
        "when ANTHROPIC_API_KEY is configured."
    ),
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    # Vercel gives every deployment its own subdomain, so preview URLs are
    # allowed by pattern rather than being listed one by one.
    allow_origins=settings.cors_origin_list,
    allow_origin_regex=r"https://.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(TranscriptParseError)
async def transcript_error_handler(_: Request, exc: TranscriptParseError) -> JSONResponse:
    return JSONResponse(status_code=422, content={"detail": str(exc)})


@app.get("/api/health", tags=["meta"])
def health() -> dict[str, str]:
    return {"status": "ok", "service": settings.app_name}


for module in (auth, meetings, notes, action_items, engagement, search, workspace):
    app.include_router(module.router, prefix=settings.api_prefix)
